# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SurveyManagement
                                 A QGIS plugin
 Digital archiving for Nigerian survey records
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-10
        git sha              : $Format:%H$
        copyright            : (C) 2026 by ASTROMAT GEO-SERVICES
        email                : ugwusochukwuma@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QDialog
from qgis.core import Qgis
import os.path
import sys

# Try to import psycopg2 with helpful error if missing
try:
    import psycopg2
    from psycopg2 import sql
    PSYCOPG2_AVAILABLE = True
except ImportError:
    PSYCOPG2_AVAILABLE = False
    psycopg2 = None
    print("WARNING: psycopg2 not installed. Database features will not work.")

# Import connection dialog
from .connection_dialog import ConnectionDialog, DatabaseManager


class SurveyManagement:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        
        # Initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SurveyManagement_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Survey Management System')
        self.db_connection = None
        self.db_manager = DatabaseManager()
        self.first_start = None
        
        # Check if we have saved settings
        self.settings = QSettings()

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('SurveyManagement', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True,
                   add_to_menu=True, add_to_toolbar=True, status_tip=None,
                   whats_this=None, parent=None):
        """Add a toolbar icon to the toolbar."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        
        # Check for psycopg2 on startup
        if not PSYCOPG2_AVAILABLE:
            self.iface.messageBar().pushMessage(
                "Warning",
                "psycopg2 not installed. Database features disabled. Run: pip install psycopg2-binary",
                level=Qgis.Warning,
                duration=10
            )

        # Main plugin action
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        if not os.path.exists(icon_path):
            # Use default icon if custom one doesn't exist
            icon_path = ':/images/themes/default/mAction.png'
            
        self.add_action(
            icon_path,
            text=self.tr(u'Survey Management System'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # Add database connection settings
        self.connection_action = QAction(
            '⚙️ Database Settings',
            self.iface.mainWindow()
        )
        self.connection_action.triggered.connect(self.show_connection_dialog)
        self.iface.addPluginToMenu(self.menu, self.connection_action)
        self.actions.append(self.connection_action)
        
        # Add test connection action
        self.test_action = QAction(
            '🔌 Test Database Connection',
            self.iface.mainWindow()
        )
        self.test_action.triggered.connect(self.test_connection)
        self.iface.addPluginToMenu(self.menu, self.test_action)
        self.actions.append(self.test_action)

        # Add help action
        self.help_action = QAction(
            '❓ Help & About',
            self.iface.mainWindow()
        )
        self.help_action.triggered.connect(self.show_help)
        self.iface.addPluginToMenu(self.menu, self.help_action)
        self.actions.append(self.help_action)

        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)
        
        # Close database connection if open
        if self.db_connection and not self.db_connection.closed:
            self.db_connection.close()

    def show_connection_dialog(self):
        """Show connection configuration dialog"""
        dialog = ConnectionDialog(self.iface.mainWindow())
        
        if dialog.exec_() == QDialog.Accepted:
            # Try to connect with new settings
            self.db_connection = self.db_manager.get_connection_from_settings()
            
            if self.db_connection:
                # Ensure database exists and create tables
                QMessageBox.information(
                    self.iface.mainWindow(),
                    "Setting Up Database",
                    "Testing connection and creating tables...\n\nThis may take a moment."
                )
                
                if self.db_manager.ensure_database_exists():
                    if self.db_manager.create_tables():
                        QMessageBox.information(
                            self.iface.mainWindow(),
                            "Success",
                            "✅ Database configured successfully!\n\n"
                            "• Database: survey_management\n"
                            "• PostGIS extension enabled\n"
                            "• All required tables created\n\n"
                            "You can now use the plugin with full functionality."
                        )
                    else:
                        QMessageBox.warning(
                            self.iface.mainWindow(),
                            "Partial Success",
                            "⚠️ Connected to database but some tables could not be created.\n\n"
                            "Please check your database permissions."
                        )
                else:
                    QMessageBox.critical(
                        self.iface.mainWindow(),
                        "Database Error",
                        "❌ Could not create or verify database.\n\n"
                        "Please check:\n"
                        "• PostgreSQL server is running\n"
                        "• You have CREATE DATABASE permissions\n"
                        "• PostGIS is available"
                    )
                
                return True
            else:
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "Connection Failed",
                    "❌ Could not connect to database.\n\n"
                    "Please check your settings:\n"
                    "• Host and port are correct\n"
                    "• Username and password are valid\n"
                    "• PostgreSQL server is running"
                )
                return False
        else:
            # User cancelled
            return False

    def connect_db(self):
        """Establish database connection using saved settings"""
        if not PSYCOPG2_AVAILABLE:
            self.iface.messageBar().pushMessage(
                "Error",
                "psycopg2 not installed. Please install psycopg2-binary",
                level=Qgis.Critical,
                duration=5
            )
            return False
        
        # Check if we have saved settings
        host = self.settings.value("survey_management/host", "")
        if not host:
            # No saved settings, show connection dialog
            return self.show_connection_dialog()
            
        try:
            # Try to get connection from settings
            self.db_connection = self.db_manager.get_connection_from_settings()
            
            if self.db_connection:
                # Test connection
                cur = self.db_connection.cursor()
                cur.execute("SELECT 1")
                cur.close()
                
                # Ensure tables exist
                self.db_manager.create_tables()
                
                return True
            else:
                # Connection failed, offer to reconfigure
                return self.handle_connection_failure()
            
        except Exception as e:
            self.iface.messageBar().pushMessage(
                "Database Error", 
                f"Could not connect: {str(e)}", 
                level=Qgis.Critical, 
                duration=5
            )
            return self.handle_connection_failure()

    def handle_connection_failure(self):
        """Handle database connection failure"""
        reply = QMessageBox.question(
            self.iface.mainWindow(),
            "Connection Failed",
            "❌ Could not connect to database.\n\n"
            "Would you like to reconfigure your connection settings?\n\n"
            "• Click YES to open connection settings\n"
            "• Click NO to continue in OFFLINE mode (limited features)",
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.Yes
        )
        
        if reply == QMessageBox.Yes:
            return self.show_connection_dialog()
        else:
            # Continue in offline mode
            QMessageBox.information(
                self.iface.mainWindow(),
                "Offline Mode",
                "⚠️ Continuing in OFFLINE mode.\n\n"
                "You can view and enter data, but it will not be saved to database.\n"
                "Use Database Settings to reconnect when database is available."
            )
            return True  # Return True for offline mode

    def test_connection(self):
        """Test database connection and show results"""
        if not PSYCOPG2_AVAILABLE:
            QMessageBox.critical(
                self.iface.mainWindow(),
                "psycopg2 Missing",
                "The psycopg2 library is not installed.\n\n"
                "Please install it by running this command in OSGeo4W Shell:\n"
                "python -m pip install psycopg2-binary"
            )
            return
        
        # Check if we have saved settings
        host = self.settings.value("survey_management/host", "")
        if not host:
            # Show connection dialog first
            reply = QMessageBox.question(
                self.iface.mainWindow(),
                "No Connection Settings",
                "No database connection settings found.\n\n"
                "Would you like to configure them now?",
                QMessageBox.Yes | QMessageBox.No
            )
            if reply == QMessageBox.Yes:
                self.show_connection_dialog()
            return
        
        # Test connection
        try:
            self.db_connection = self.db_manager.get_connection_from_settings()
            
            if self.db_connection:
                cur = self.db_connection.cursor()
                
                # Get PostgreSQL version
                cur.execute("SELECT version()")
                version = cur.fetchone()[0]
                
                # Get PostGIS version
                cur.execute("SELECT PostGIS_Version()")
                postgis_version = cur.fetchone()[0]
                
                # Get table counts
                tables = ['surveys', 'survey_points', 'survey_boundaries', 'survey_documents']
                counts = []
                for table in tables:
                    cur.execute(f"SELECT COUNT(*) FROM {table}")
                    count = cur.fetchone()[0]
                    counts.append(f"• {table}: {count} records")
                
                cur.close()
                
                # Show success message with details
                QMessageBox.information(
                    self.iface.mainWindow(),
                    "Connection Successful",
                    f"✅ Connected to database!\n\n"
                    f"📊 PostgreSQL: {version[:100]}...\n"
                    f"🗺️ PostGIS: {postgis_version}\n\n"
                    f"📋 Table Statistics:\n" + "\n".join(counts)
                )
            else:
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "Connection Failed",
                    "❌ Could not connect to database.\n\n"
                    "Please check your settings in Database Settings menu."
                )
            
        except Exception as e:
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Connection Error",
                f"❌ Error testing connection:\n\n{str(e)}"
            )

    def show_help(self):
        """Show help and about dialog"""
        help_text = """
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h1 { color: #2c3e50; font-size: 18pt; }
                h2 { color: #27ae60; font-size: 14pt; margin-top: 20px; }
                ul { margin-left: 20px; }
                li { margin: 5px 0; }
                .footer { margin-top: 30px; color: #7f8c8d; font-style: italic; }
            </style>
        </head>
        <body>
            <h1>🏛️ Survey Management System</h1>
            <p><b>Version:</b> 1.0.0</p>
            <p><b>Copyright:</b> 2026 ASTROMAT GEO-SERVICES</p>
            <p><b>Email:</b> ugwusochukwuma@gmail.com</p>
            
            <h2>📋 About</h2>
            <p>A comprehensive digital archiving solution for Nigerian survey records, 
            integrated with QGIS for spatial visualization and PostgreSQL/PostGIS for 
            50-year durable storage.</p>
            
            <h2>✨ Features</h2>
            <ul>
                <li>📋 Survey metadata management</li>
                <li>📍 Direct coordinate input</li>
                <li>📐 Bearing & distance traverse calculator</li>
                <li>📄 Document management with checksum verification</li>
                <li>🗄️ Direct PostGIS layer loading</li>
                <li>🔍 Advanced search and retrieval</li>
                <li>🇳🇬 Nigerian CRS presets (Minna, etc.)</li>
                <li>✅ 50-year data integrity with MD5 checksums</li>
            </ul>
            
            <h2>🔌 Database Setup</h2>
            <p>The plugin automatically creates all required tables when you first connect.
            Simply enter your PostgreSQL connection details and the plugin will:</p>
            <ul>
                <li>Create the 'survey_management' database if missing</li>
                <li>Enable PostGIS extension</li>
                <li>Create all 6 required tables</li>
                <li>Set up spatial indexes</li>
            </ul>
            
            <h2>📚 Quick Start</h2>
            <ol>
                <li>Click the plugin icon 🏛️</li>
                <li>Configure database connection (first time only)</li>
                <li>Select your CRS (default: EPSG:26332 Minna Mid Belt)</li>
                <li>Enter survey metadata</li>
                <li>Add coordinates or traverse data</li>
                <li>Plot on map to verify</li>
                <li>Save to database</li>
            </ol>
            
            <div class="footer">
                "Preserving Nigeria's surveying heritage, one coordinate at a time."
            </div>
        </body>
        </html>
        """
        
        QMessageBox.about(
            self.iface.mainWindow(),
            "About Survey Management System",
            help_text
        )

    def run(self):
        """Run the main plugin dialog"""
        # Show message that we're starting
        self.iface.messageBar().pushMessage(
            "Info", 
            "Opening Survey Management System...", 
            level=Qgis.Info, 
            duration=2
        )
        
        # Check psycopg2
        if not PSYCOPG2_AVAILABLE:
            reply = QMessageBox.question(
                self.iface.mainWindow(),
                "psycopg2 Missing",
                "The psycopg2 library is not installed.\n\n"
                "Would you like to continue in offline mode?\n"
                "(Database features will be disabled)",
                QMessageBox.Yes | QMessageBox.No
            )
            if reply == QMessageBox.No:
                return
            db_connection = None
        else:
            # Try to connect to database
            if not self.connect_db():
                # connect_db already handles user interaction
                return
            db_connection = self.db_connection
        
        # Import the dialog here to avoid circular imports
        try:
            from .SurveyManagement_dialog import SurveyManagementDialog
        except ImportError as e:
            self.iface.messageBar().pushMessage(
                "Error", 
                f"Could not load dialog: {str(e)}", 
                level=Qgis.Critical, 
                duration=5
            )
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Plugin Error",
                f"Failed to load dialog module:\n{str(e)}\n\n"
                f"Please reinstall the plugin."
            )
            return
        
        # Create and show the dialog
        try:
            # Pass None for parent to make it a top-level window
            self.dialog = SurveyManagementDialog(self.iface.mainWindow(), db_connection)
            
            # Set window modality to ApplicationModal to block interaction with QGIS
            self.dialog.setWindowModality(Qt.ApplicationModal)
            
            # Show dialog
            self.dialog.show()
            
        except Exception as e:
            self.iface.messageBar().pushMessage(
                "Error", 
                f"Dialog error: {str(e)}", 
                level=Qgis.Critical, 
                duration=5
            )
            import traceback
            traceback.print_exc()
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Plugin Error",
                f"An unexpected error occurred:\n\n{str(e)}\n\n"
                f"Please check the Python console for details."
            )